---
- name: Install Docker and Docker Compose on Ubuntu
  hosts: all
  become: true

  tasks:
    - name: Check if Docker is already installed
      command: which docker
      register: docker_check
      ignore_errors: true

    - name: Install prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: true
      when: docker_check.rc != 0

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: docker_check.rc != 0

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
        filename: docker
      when: docker_check.rc != 0

    - name: Update apt cache
      apt:
        update_cache: true
      when: docker_check.rc != 0

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
      when: docker_check.rc != 0

    - name: Check if Docker Compose plugin is installed
      command: docker compose version
      register: docker_compose_check
      ignore_errors: true

    - name: Install Docker Compose plugin
      apt:
        name: docker-compose-plugin
        state: latest
      when: docker_compose_check.rc != 0

    - name: Ensure Docker is started and enabled
      service:
        name: docker
        state: started
        enabled: true